# Generated by Django 5.0.2 on 2024-03-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priority_choice', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=50)),
                ('status_choice', models.CharField(choices=[('done', 'Выполнено'), ('cancelled', 'Отменено'), ('postponed', 'Отложено')], max_length=50)),
            ],
        ),
    ]
